dir.create("data")
dir.create("data_output")
dir.create("fig_output")
dir.create("scripts")
download.file("https://ndownloader.figshare.com/files/11492171", "data/SAFI_clean.csv", mode = "wb")
install.packages("tidyverse")